### ISSUE TITLE
Add a field, `places_id` and push it out to CartoDB

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#73]
We should append `n` or `w` or `a` to the front of the places_id.

Thoughts, @jimmyrocks?

**Comment by jimmyrocks** [comment]
Right now the places_id field exists, it's just null (it used to be used
for nps:places_id)
I was considering getting rid of it, but it's trivial to change it to be
the osm_id prepended by the type
(n, w, or r)

Consider it done

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-api/commit/bf2953f62acaaa05db843fa5aec050ac575a15d7

Done in code, I'll close it when I update what's in CartoDB

**Comment by nateirwin** [comment]
Can we just run an update query against CartoDB? Or is that going to break the CRON sync?

**Comment by jimmyrocks** [comment]
It's actually done other than running that query, so I'll run it and close
it

**Comment by nateirwin** [comment]
Looks like places_id still isn't in there? At least not in the "roads" table.
